server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///IdeaProjects/confsvr2/src/main/resources/config/licensingservice